### ISSUE TITLE
Prevent payment gateway radio selection from showing when only one gateway active

### ISSUE THREAD

**Issue by mindctrl** [Ipstenu/edd-prevent-eu-checkout#13]
When only one gateway is active in EDD, the option to select a payment gateway is not shown on the checkout page. [Reference](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/77fbbdffdaceebb9c095f5bbb9bdd23761920a09/includes/gateways/functions.php#L321-L335). When this plugin is active, it shows up with only one gateway enabled.

![image](https://cloud.githubusercontent.com/assets/1254870/10110487/88fda8ae-639b-11e5-82d7-ffe240019e8c.png)

That's caused by `add_filter( 'edd_show_gateways', array( $this, 'can_checkout' ) );` [here](https://github.com/Ipstenu/edd-prevent-eu-checkout/blob/master/edd-prevent-checkout.php#L88).

Since the plugin already filters edd_can_checkout to prevent checkouts, I think it's safe to remove the additional check that's causing the payment gateway selection to show up with only one gateway active.

Thoughts @Ipstenu and @pippinsplugins.

**Comment by Ipstenu** [comment]
What shows up when the plugin is disabled?

Because you just said "When only one gateway is active in EDD, [and] this plugin is active, it shows up with only one gateway enabled."

Which ... Well yeah :)  So what were you expected to show and what happens without the plugin?

**Comment by mindctrl** [comment]
@Ipstenu when this plugin is disabled, EDD doesn't show the radio button because there's no need for it when only one payment gateway is active. There's no choice to be made. But, when enabling this plugin it's forcing the radio button to show.

**Comment by Ipstenu** [comment]
That seems ... Very odd and I'm not entirely sure the fix is this plugin. It sounds more like the filter on EDD's end is misbehaving. @pippinsplugins am I missing something there? I remember putting it in there because if I don't, things showed weirdly in some setups.

I wonder if that's actually related to `edd_show_payment_icons` because that does a check for payment gateways too.

**Comment by Ipstenu** [comment]
Well this took a while to understand why it was derping.

```
			// prevent payment select box from showing
			if ( edd_show_gateways() ) {
				add_filter( 'edd_show_gateways', array( $this, 'can_checkout' ) );
			}

```

The issue is that can_checkout returns TRUE if you're not in the EU (right? right...) but in the case of showing gateways, the true assertion was telling IT to show. Which... No.

So now it checks "if edd_show_gateways is going to show, let's make sure it's supposed to show."

Version 1.1.2 on the way as soon as I make sure this doesn't break anything else.
